spring:
  application:
    name: sandbox

  datasource:
    url: jdbc:mysql://localhost:3306/sandbox_db?useSSL=false&serverTimezone=Asia/Seoul&useCursorFetch=true&defaultFetchSize=1000
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
